version: "3.7"
services:
    producer:
        container_name: producer-overflow
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
        image: producer-overflow:latest
        depends_on:
            - kafka1
        volumes:
            - "./producer/:/app"
    neo4j:
        container_name: neo4j-overflow
        build:
            context: .
            dockerfile: ./docker/neo4j/Dockerfile
        image: neo4j-overflow:latest
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - "./neo4j/data:/data"
    zookeeper:
        container_name: zookeeper
        build:
            context: .
            dockerfile: ./docker/zookeeper/Dockerfile
        image: zookeeper-overflow:latest
        ports:
            - "2181:2181"
    kafka1:
        container_name: kafka1
        build:
            context: .
            dockerfile: "./docker/kafka/Dockerfile"
        image: kafka-overflow:latest
        depends_on:
            - zookeeper
        restart: always
        ports:
            - "9092:9092"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 192.168.99.123
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "questions:1::compact"
          KAFKA_MESSAGE_MAX_BYTES: 1000000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
